### ISSUE TITLE
Change FieldsParam `paths` to `fields` 

### ISSUE THREAD

**Issue by MacMcIrish** [blackflux/lambda-serverless-api#668]
Was previously `paths` to mirror `obj-paths`, which has been replaced by `object-fields`

On update, also replace `obj-paths` dependency with `object-fields`

**Comment by simlu** [comment]
Consider renaming to `allowedFields`?

**Comment by krackerman** [comment]
work was done in this PR https://github.com/blackflux/lambda-serverless-api/pull/674
