### ISSUE TITLE
Support for ENUM param

### ISSUE THREAD

**Issue by MacMcIrish** [blackflux/lambda-serverless-api#857]
We've been using `FieldsParam` or `RegEx` as an alternative for what would be the `ENUM` param, but native support would be much better if we could provide a list of valid entries.

`FieldsParam` is incorrect because it theoretically allows the user to supply a comma separated list of the allowed values, and now that the library has been updated, this is served as a list requiring further validation in endpoint logic.

`RegEx` is unmaintainable for large lists, such as timezone names.

**Comment by simlu** [comment]
Done in https://github.com/blackflux/lambda-serverless-api/pull/859
